import pandas as pd
import numpy as np
import traceback
from src.strategies.schemas import StrategyRecipe
from src.logger import LabLogger
from src.ta_lib import TALib
import asyncio

class StrategyParser:
    def parse_and_execute(self, df: pd.DataFrame, strategy: StrategyRecipe) -> pd.DataFrame:
        """
        Applies indicators and logic to the DataFrame.
        Returns the DF with 'signal' column (-1, 0, 1).
        """
        # Async helper to log safely from sync context
        def log_sync(msg, details=None):
            try:
                loop = asyncio.get_event_loop()
                if loop.is_running():
                    loop.create_task(LabLogger.log("BACKTEST", msg, details))
            except:
                pass

        # Work on a copy
        df = df.copy()

        # 1. Apply Indicators
        for ind in strategy.indicators:
            try:
                if not hasattr(TALib, ind.name):
                    msg = f"Indicator '{ind.name}' not found in TALib."
                    print(f"Warning: {msg}")
                    log_sync(msg)
                    continue

                # Call the indicator function from TALib
                method = getattr(TALib, ind.name)

                # Check signature to see if it needs OHLC or just Close
                # Simplified: pass kwargs + series/ohlc based on name
                # Most indicators take 'close' (series)
                params = ind.params.copy()

                if ind.name in ['atr', 'adx']:
                    # These need high, low, close
                    result = method(df['high'], df['low'], df['close'], **params)
                else:
                    # Assume single series (usually close)
                    # Some might need 'volume' later, but for now mostly close
                    target = df['close']
                    # If params specifies source column? Not supported yet.
                    result = method(target, **params)

                # Explicit renaming:
                if ind.col_name:
                    if isinstance(result, pd.Series):
                        df[ind.col_name] = result
                    elif isinstance(result, pd.DataFrame):
                        # Check if columns already match the col_name to avoid redundancy (e.g. ADX_14 -> ADX_14_ADX_14)
                        # If the col_name is roughly contained in the columns, we assume it's just an alias or the same.
                        # Actually, better logic: If ind.col_name is exactly the same as one of the columns, don't prefix.
                        # Or if we blindly prefix, we break logic strings.
                        # Strategy: Only prefix if it doesn't look like the indicator logic already handles unique naming.
                        # BUT, for ADX, TALib returns `ADX_14`. If col_name is `ADX_14`, we get `ADX_14_ADX_14`.

                        # Fix: If any column in result *equals* ind.col_name, do not prefix.
                        if ind.col_name in result.columns:
                             df = pd.concat([df, result], axis=1)
                        else:
                             # Standard prefixing for disambiguation (e.g. macd_1 -> macd_1_MACD...)
                             # But wait, if logic uses `ADX_14` and we prefix to `MyADX_ADX_14`, logic fails.
                             # If the user (AI) provided `col_name="ADX_14"` expecting that to be the variable name,
                             # we should ensure `ADX_14` exists.

                             # If result has 1 column and it's not named col_name, rename it?
                             # ADX returns 3 columns.

                             # Safe approach: Concat ORIGINAL columns first (so standard names exist),
                             # AND if meaningful, add alias? No, that duplicates data.

                             # If the AI sets col_name="ADX_14", it essentially wants the result to be accessible as such.
                             # TALib already names it "ADX_14".
                             # So if col_name starts with the indicator name or seems redundant, ignore it?

                             # Let's just NOT prefix if the col_name is already part of the column name?
                             # Or better: logic strings generated by AI usually match the default TALib output (Smart Aliasing).
                             # If AI forces a col_name, it might be trying to "Help", but it hurts.

                             # Decision: If result is DataFrame, we DO NOT prefix. We trust TALib's unique naming (which includes length).
                             # Adding `col_name` as a prefix is causing more harm than good for multi-output indicators.
                             # If multiple ADX indicators exist (ADX_14, ADX_20), TALib handles distinct names.

                             # Exception: If user specifically named it "MyADX", they might use "MyADX_ADX_14"?
                             # Unlikely AI does that. AI usually assumes "ADX_14".

                             # Fix: Just concat.
                             df = pd.concat([df, result], axis=1)
                else:
                     if result is not None:
                        df = pd.concat([df, result], axis=1)

            except Exception as e:
                msg = f"Error calculating indicator '{ind.name}': {e}"
                print(msg)
                traceback.print_exc()
                log_sync(msg)

        # 2. Sanitize Column Names (Fix potential dots)
        # Custom TALib shouldn't produce dots, but safe to keep

        rename_map = {}
        for col in df.columns:
            if "." in col:
                new_col = col.replace(".", "_")
                rename_map[col] = new_col

        if rename_map:
            df.rename(columns=rename_map, inplace=True)

        # 3. Sanitize Logic Strings
        entry_logic = strategy.entry_logic
        exit_logic = strategy.exit_logic

        # Additional Sanitization: Replace . with _ in logic strings if they match column pattern
        # This handles cases where logic string has "2.0" but column was renamed to "2_0"
        # However, we must be careful not to replace actual floats like 0.5
        # The rename_map handles columns that *existed* and were renamed.
        # But if the user typed "BBU_20_2.0" manually in the logic, we need to map it.

        for old, new in rename_map.items():
            entry_logic = entry_logic.replace(old, new)
            exit_logic = exit_logic.replace(old, new)

        # 4. Evaluate Logic
        df['signal'] = 0

        try:
            entry_mask = df.eval(entry_logic)
            exit_mask = df.eval(exit_logic)

            # Check Overlap
            overlap = entry_mask & exit_mask
            if overlap.any():
                overlap_count = overlap.sum()
                log_sync(f"Logic Warning: Entry and Exit logic overlap on {overlap_count} candles. Exit takes precedence.")

            # Apply signals
            df.loc[entry_mask, 'signal'] = 1
            df.loc[exit_mask, 'signal'] = -1

            # Ensure integer type
            df['signal'] = df['signal'].astype(int)

            # Log signal counts
            buy_count = entry_mask.sum()
            sell_count = exit_mask.sum()
            final_signal_counts = df['signal'].value_counts().to_dict()
            log_sync(f"Logic Evaluated: {buy_count} potential Buys, {sell_count} potential Sells. Final Signals: {final_signal_counts}")

        except Exception as e:
            msg = f"Logic Evaluation Error: {e}"
            print(msg)
            traceback.print_exc()
            log_sync(msg, {"entry": entry_logic, "exit": exit_logic})

        # Final Clean: Remove duplicate columns if any crept in
        df = df.loc[:, ~df.columns.duplicated()]
        return df
